// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// get_trigonometric_summand_3_parameter
NumericVector get_trigonometric_summand_3_parameter(NumericVector x, int J_1, int J_2, int J_3);
RcppExport SEXP _EPF_get_trigonometric_summand_3_parameter(SEXP xSEXP, SEXP J_1SEXP, SEXP J_2SEXP, SEXP J_3SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type J_1(J_1SEXP);
    Rcpp::traits::input_parameter< int >::type J_2(J_2SEXP);
    Rcpp::traits::input_parameter< int >::type J_3(J_3SEXP);
    rcpp_result_gen = Rcpp::wrap(get_trigonometric_summand_3_parameter(x, J_1, J_2, J_3));
    return rcpp_result_gen;
END_RCPP
}
// get_trigonometric_summand_4_parameter
NumericVector get_trigonometric_summand_4_parameter(NumericVector x, int J_1, int J_2, int J_3, int J_4);
RcppExport SEXP _EPF_get_trigonometric_summand_4_parameter(SEXP xSEXP, SEXP J_1SEXP, SEXP J_2SEXP, SEXP J_3SEXP, SEXP J_4SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type J_1(J_1SEXP);
    Rcpp::traits::input_parameter< int >::type J_2(J_2SEXP);
    Rcpp::traits::input_parameter< int >::type J_3(J_3SEXP);
    Rcpp::traits::input_parameter< int >::type J_4(J_4SEXP);
    rcpp_result_gen = Rcpp::wrap(get_trigonometric_summand_4_parameter(x, J_1, J_2, J_3, J_4));
    return rcpp_result_gen;
END_RCPP
}
// ChevTrA
NumericVector ChevTrA(NumericVector T);
RcppExport SEXP _EPF_ChevTrA(SEXP TSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type T(TSEXP);
    rcpp_result_gen = Rcpp::wrap(ChevTrA(T));
    return rcpp_result_gen;
END_RCPP
}
// ChevTrB
NumericVector ChevTrB(NumericVector T);
RcppExport SEXP _EPF_ChevTrB(SEXP TSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type T(TSEXP);
    rcpp_result_gen = Rcpp::wrap(ChevTrB(T));
    return rcpp_result_gen;
END_RCPP
}
// SineTr
NumericVector SineTr(NumericVector T);
RcppExport SEXP _EPF_SineTr(SEXP TSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type T(TSEXP);
    rcpp_result_gen = Rcpp::wrap(SineTr(T));
    return rcpp_result_gen;
END_RCPP
}
// OddNegTr
NumericVector OddNegTr(NumericVector T);
RcppExport SEXP _EPF_OddNegTr(SEXP TSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type T(TSEXP);
    rcpp_result_gen = Rcpp::wrap(OddNegTr(T));
    return rcpp_result_gen;
END_RCPP
}
// CosineSumTr
NumericVector CosineSumTr(NumericMatrix TT);
RcppExport SEXP _EPF_CosineSumTr(SEXP TTSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type TT(TTSEXP);
    rcpp_result_gen = Rcpp::wrap(CosineSumTr(TT));
    return rcpp_result_gen;
END_RCPP
}
// SineSumTr
NumericVector SineSumTr(NumericMatrix TT);
RcppExport SEXP _EPF_SineSumTr(SEXP TTSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type TT(TTSEXP);
    rcpp_result_gen = Rcpp::wrap(SineSumTr(TT));
    return rcpp_result_gen;
END_RCPP
}
// get_quantile_multiplier
NumericVector get_quantile_multiplier(double m, int J);
RcppExport SEXP _EPF_get_quantile_multiplier(SEXP mSEXP, SEXP JSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    rcpp_result_gen = Rcpp::wrap(get_quantile_multiplier(m, J));
    return rcpp_result_gen;
END_RCPP
}
// get_lowess_multiplier
NumericVector get_lowess_multiplier(double x, double h, int J);
RcppExport SEXP _EPF_get_lowess_multiplier(SEXP xSEXP, SEXP hSEXP, SEXP JSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    rcpp_result_gen = Rcpp::wrap(get_lowess_multiplier(x, h, J));
    return rcpp_result_gen;
END_RCPP
}
// get_loess_powers
NumericMatrix get_loess_powers(NumericVector x, NumericVector y, NumericVector x_0, NumericVector h, int K);
RcppExport SEXP _EPF_get_loess_powers(SEXP xSEXP, SEXP ySEXP, SEXP x_0SEXP, SEXP hSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_0(x_0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type h(hSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(get_loess_powers(x, y, x_0, h, K));
    return rcpp_result_gen;
END_RCPP
}
// get_loess_match
NumericVector get_loess_match(NumericVector x, NumericVector x_0, double M);
RcppExport SEXP _EPF_get_loess_match(SEXP xSEXP, SEXP x_0SEXP, SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_0(x_0SEXP);
    Rcpp::traits::input_parameter< double >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(get_loess_match(x, x_0, M));
    return rcpp_result_gen;
END_RCPP
}
// get_kdtree_summand_2_parameter
NumericVector get_kdtree_summand_2_parameter(NumericMatrix X, int J_1, int J_2);
RcppExport SEXP _EPF_get_kdtree_summand_2_parameter(SEXP XSEXP, SEXP J_1SEXP, SEXP J_2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type J_1(J_1SEXP);
    Rcpp::traits::input_parameter< int >::type J_2(J_2SEXP);
    rcpp_result_gen = Rcpp::wrap(get_kdtree_summand_2_parameter(X, J_1, J_2));
    return rcpp_result_gen;
END_RCPP
}
// get_kdtree_summand_3_parameter
NumericVector get_kdtree_summand_3_parameter(NumericMatrix X, int J_1, int J_2, int J_3);
RcppExport SEXP _EPF_get_kdtree_summand_3_parameter(SEXP XSEXP, SEXP J_1SEXP, SEXP J_2SEXP, SEXP J_3SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type J_1(J_1SEXP);
    Rcpp::traits::input_parameter< int >::type J_2(J_2SEXP);
    Rcpp::traits::input_parameter< int >::type J_3(J_3SEXP);
    rcpp_result_gen = Rcpp::wrap(get_kdtree_summand_3_parameter(X, J_1, J_2, J_3));
    return rcpp_result_gen;
END_RCPP
}
// get_kdtree_multiplier
NumericVector get_kdtree_multiplier(float a, float b, int J);
RcppExport SEXP _EPF_get_kdtree_multiplier(SEXP aSEXP, SEXP bSEXP, SEXP JSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< float >::type a(aSEXP);
    Rcpp::traits::input_parameter< float >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    rcpp_result_gen = Rcpp::wrap(get_kdtree_multiplier(a, b, J));
    return rcpp_result_gen;
END_RCPP
}
// kdtree_medians2cellcounts
NumericVector kdtree_medians2cellcounts(NumericMatrix data, NumericMatrix medians);
RcppExport SEXP _EPF_kdtree_medians2cellcounts(SEXP dataSEXP, SEXP mediansSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type medians(mediansSEXP);
    rcpp_result_gen = Rcpp::wrap(kdtree_medians2cellcounts(data, medians));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_EPF_get_trigonometric_summand_3_parameter", (DL_FUNC) &_EPF_get_trigonometric_summand_3_parameter, 4},
    {"_EPF_get_trigonometric_summand_4_parameter", (DL_FUNC) &_EPF_get_trigonometric_summand_4_parameter, 5},
    {"_EPF_ChevTrA", (DL_FUNC) &_EPF_ChevTrA, 1},
    {"_EPF_ChevTrB", (DL_FUNC) &_EPF_ChevTrB, 1},
    {"_EPF_SineTr", (DL_FUNC) &_EPF_SineTr, 1},
    {"_EPF_OddNegTr", (DL_FUNC) &_EPF_OddNegTr, 1},
    {"_EPF_CosineSumTr", (DL_FUNC) &_EPF_CosineSumTr, 1},
    {"_EPF_SineSumTr", (DL_FUNC) &_EPF_SineSumTr, 1},
    {"_EPF_get_quantile_multiplier", (DL_FUNC) &_EPF_get_quantile_multiplier, 2},
    {"_EPF_get_lowess_multiplier", (DL_FUNC) &_EPF_get_lowess_multiplier, 3},
    {"_EPF_get_loess_powers", (DL_FUNC) &_EPF_get_loess_powers, 5},
    {"_EPF_get_loess_match", (DL_FUNC) &_EPF_get_loess_match, 3},
    {"_EPF_get_kdtree_summand_2_parameter", (DL_FUNC) &_EPF_get_kdtree_summand_2_parameter, 3},
    {"_EPF_get_kdtree_summand_3_parameter", (DL_FUNC) &_EPF_get_kdtree_summand_3_parameter, 4},
    {"_EPF_get_kdtree_multiplier", (DL_FUNC) &_EPF_get_kdtree_multiplier, 3},
    {"_EPF_kdtree_medians2cellcounts", (DL_FUNC) &_EPF_kdtree_medians2cellcounts, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_EPF(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
