# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_trigonometric_summand_3_parameter <- function(x, J_1, J_2, J_3) {
    .Call(`_EPF_get_trigonometric_summand_3_parameter`, x, J_1, J_2, J_3)
}

get_trigonometric_summand_4_parameter <- function(x, J_1, J_2, J_3, J_4) {
    .Call(`_EPF_get_trigonometric_summand_4_parameter`, x, J_1, J_2, J_3, J_4)
}

ChevTrA <- function(T) {
    .Call(`_EPF_ChevTrA`, T)
}

ChevTrB <- function(T) {
    .Call(`_EPF_ChevTrB`, T)
}

SineTr <- function(T) {
    .Call(`_EPF_SineTr`, T)
}

OddNegTr <- function(T) {
    .Call(`_EPF_OddNegTr`, T)
}

CosineSumTr <- function(TT) {
    .Call(`_EPF_CosineSumTr`, TT)
}

SineSumTr <- function(TT) {
    .Call(`_EPF_SineSumTr`, TT)
}

get_quantile_multiplier <- function(m, J) {
    .Call(`_EPF_get_quantile_multiplier`, m, J)
}

get_lowess_multiplier <- function(x, h, J) {
    .Call(`_EPF_get_lowess_multiplier`, x, h, J)
}

get_loess_powers <- function(x, y, x_0, h, K) {
    .Call(`_EPF_get_loess_powers`, x, y, x_0, h, K)
}

get_loess_match <- function(x, x_0, M) {
    .Call(`_EPF_get_loess_match`, x, x_0, M)
}

get_kdtree_summand_2_parameter <- function(X, J_1, J_2) {
    .Call(`_EPF_get_kdtree_summand_2_parameter`, X, J_1, J_2)
}

get_kdtree_summand_3_parameter <- function(X, J_1, J_2, J_3) {
    .Call(`_EPF_get_kdtree_summand_3_parameter`, X, J_1, J_2, J_3)
}

get_kdtree_multiplier <- function(a, b, J) {
    .Call(`_EPF_get_kdtree_multiplier`, a, b, J)
}

kdtree_medians2cellcounts <- function(data, medians) {
    .Call(`_EPF_kdtree_medians2cellcounts`, data, medians)
}

